
from unit import *

food_list = [
        #["apfel", "Apfel", "apple", "manzana"],
        #["aepfel", "Äpfel", "apples", "manzanas"],
        #["aprikose", "Aprikose", "apricot", "damasco"],
        #["aubergine", "Aubergine", "aubergine", "berenjena"],
        #["avocado", "Avocado", "avocado", "aguacate"],
        #["backkakao", "Backkakao", "cocoa powder", "cacao en polvo"],
        ["backpulver", tl, 3, "Backpulver", "baking powder", "polvo de hornear"], #1 pkg 15g, 1 tl 3g
        #["Backstabil", "backstabil", "baking stable", "estable para hornear"],
        #["backzutaten", "Backzutaten", "baking ingredients", "ingredientes para hornear"],
        #["baguette", "Baguette", "baguette", "junquillo"],
        #["balsamico", "Balsamico", "balsamic", "balsámico"],
        #["banane", "Banane", "banana", "banana"],
        #["bananen", "Bananen", "bananas", "bananas"],
        #["basilikum", "Basilikum", "bazil", "albahaca"],
        #["bechamelsosse", "Bechamelsoße", "bechamel sauce", "salsa bechamel"],
        #["becher", "Becher", "mug", "vasos"],
        #["beeren", "Beeren", "berries", "bayas"],
        #["bier", "Bier", "beer", "cerveza"],
        #["birne", "Birne", "pear", "pera"],
        #["birnen", "Birnen", "pears", "peras"],
        #["blatt", "Blatt", "leaf", "hoja"],
        #["blaubeeren", "Blaubeeren", "blueberries", "arándanos"],
        #["blumenkohl", "Blumenkohl", "cauliflower", "coliflor"],
        #["bohnen", "Bohnen", "beans", "frijoles"],
        #["braun", "braun", "brown", "marrón"],
        #["brezel", "Brezel", "pretzel", "rosquilla"],
        #["brie", "Brie", "brie cheese", "queso brie"],
        #["brokkoli", "Brokkoli", "broccoli", "broccoli"],
        #["brot", "Brot", "bread", "pan"],
        #["broetchen", "Brötchen", "bread roll", "panecillo"],
        #["bruehe", "Brühe", "broth", "caldo"],
        #["bund", "Bund", "bunch", "haz"],
        #["butter", "Butter", "butter", "mantequilla"],
        #["buttermilch", "Buttermilch", "buttermilk", "suero de leche"],
        #["camembert", "Camembert", "camembert cheese", "queso camembert"],
        #["carrotcake", "Karottenkuchen", "carrot cake", "queque de zanahoria"],
        #["cashew", "Cashew", "cashew", "anacardo"],
        #["cayennepfeffer", "Cayennepfeffer", "cayenne pepper", "pimienta de cayena"],
        #["champignons", "Champignons", "mushroom", "champiñon"],
        #["cheddar", "Cheddar", "cheddar cheese", "queso cheddar"],
        #["chili", "Chili", "chili", "ají"],
        #["chilipaste", "Chilipaste", "chili paste", "pasta de ají"],
        #["cocktail", "Cocktail", "cocktail", "cóctel"],
        #["cranberries", "Cranberries", "cranberry", "arándano rojo"],
        #["cremefraiche", "Creme fraiche", "creme fraiche cheese", "queso creme fraich"],
        #["croissant", "Croissant", "croissant", "croissant"],
        #["curry", "Curry", "curry", "curry"],
        #["currypaste", "Currypaste", "curry paste", "pasta de curry"],
        #["datteln", "Datteln", "dates", "dátiles"],
        #["dill", "Dill", "dill", "eneldo"],
        #["dose", "Dose", "can", "lata"],
        #["dosentomaten", "Dosentomaten", "canned tomatos", "tomates enlatados"],
        ["ei", st, 100, "Ei", "egg", "huevo"],
        ["eier", st, 100, "Eier", "eggs", "huevos"],
        #["eigelb", "Eigelb", "egg yolk", "yema"],
        #["einige", "einige", "some", "algunos"],
        #["eiweiss", "Eiweiss", "egg white", "clara de huevo"],
        #["erdbeeren", "Erdbeeren", "strawberries", "frutillas"],
        #["erdnuesse", "Erdnüsse", "peanuts", "maní"],
        #["erbsen", "Erbsen", "peas", "arvejos"],
        #["essig", "Essig", "vinegar", "vinagre"],
        #["feldsalat", "Feldsalat", "lamb's lettuce", "hojas de canónigos"],
        #["festkochend", "festkochend", "festkochend", "festkochend"],
        #["fett", "Fett", "fat", "grasa"],
        #["fisch", "Fisch", "fish", "pescado"],
        #["fluessigkeiten", "Flüssigkeiten", "liquids", "líquidos"],
        #["forelle", "Forelle", "trout", "trucha"],
        #["fruechtemuesli", "Früchtemüsli", "fruit cereal", "cereal de frutas"],
        #["fruechte", "Früchte", "fruit", "frutas"],
        #["frisch", "frisch", "fresh", "fresco"],
        #["frischgerieben", "frisch gerieben", "freshly grated", "recien rallado"],
        #["frischkaese", "Frischkäse", "cream cheese", "queso fresco"],
        #["fruehlingszwiebel", "Frühlingszwiebeln", "spring onions", "cebolleta"],
        #["fuellung", "Füllung", "filling", "relleno"],
        #["gefroren", "gefroren", "frozen", "congelado"],
        #["gehackt", "gehackt", "chopped", "picado"],
        #["gekocht", "gekocht", "cooked", "cocido"],
        #["gelatine", "Gelatine", "gelatine", "gelatina"],
        #["gelb", "gelb", "yellow", "amarillo"],
        #["gelierzucker", "Gelierzucker", "jellied sugar", "azucar en gelatina"],
        #["gemahlen", "gemahlen", "ground", "molido"],
        #["gemischt", "gemischt", "mixed", "mezclado"],
        #["gemuese", "Gemüse", "vegetables", "vegetales"],
        #["gemuesebruehe", "Gemüsebrühe", "vegetable broth", "caldo de vegetales"],
        #["gerieben", "gerieben", "grated", "rallado"],
        #["geschaelt", "geschält", "peeled", "pelado"],
        #["geschmolzen", "geschmolzen", "melted", "derretido"],
        #["getreideprodukte", "Getreideprodukte", "grains", "productos de granos"],
        #["getrocknet", "getrocknet", "dried", "secado"],
        #["gezuckert", "gezuckert", "sugared", "azucarado"],
        #["grob", "grob", "coarse", "grueso"],
        #["gross", "groß", "big", "grande"],
        #["gruen", "grün", "green", "verde"],
        #["gurke", "Gurke", "cucumber", "pepino"],
        #["gurken", "Gurken", "cucumber", "pepino"],
        #["gouda", "Gouda", "gouda cheese", "queso gouda"],
        #["huelsenfruechte", "Hülsenfrüchte", "legumes", "legumbre"],
        #["haferflocken", "Haferflocken", "oatmeal", "avena"],
        #["haselnuesse", "Haselnüsse", "hazelnuts", "avellanas"],
        #["hefe", "Hefe", "yeast", "levadura"],
        #["himbeer", "Himbeere", "raspberry", "frambuesa"],
        #["himbeeren", "Himbeeren", "raspberries", "frambuesas"],
        #["honig", "Honig", "honey", "miel"],
        #["honigmelone", "Honigmelone", "honeydew melon", "melón dulce"],
        #["hydration", "Hydration", "hydration", "hidración"],
        #["ingwer", "Ingwer", "ginger", "gengibre"],
        #["joghurt", "Joghurt", "yoghurt", "yogur"],
        #["kardamom", "Kardamom", "cardamom", "cardamomo"],
        #["kartoffel", "Kartoffel", "potato", "pápa"],
        #["kartoffeln", "Kartoffeln", "potatoes", "pápas"],
        #["kaese", "Käse", "cheese", "queso"],
        #["keksboden", "Keksboden", "cookie base", "base de galletas"],
        #["kerne", "Kerne", "seeds", "semillas"],
        #["katzenzungen", "Katzenzungen", "cat tongue cookies", "lenguas de gato"],
        #["kidneybohnen", "Kidneybohnen", "kidney beans", "frijoles"],
        #["kirschen", "Kirschen", "cherries", "cereza"],
        #["kiwi", "Kiwi", "kiwi", "kiwi"],
        #["Klein", "klein", "small", "pequeño"],
        #["knoblauch", "Knoblauch", "garlic", "ajo"],
        #["kohlrabi", "Kohlrabi", "kohlrabi", "colinabo"],
        #["kokos", "Kokos", "coconut", "coco"],
        #["kokosmilch", "Kokosmilch", "coconut milk", "leche de coco"],
        #["kondensmilch", "Kondensmilch", "condensed milk", "leche condensada"],
        #["knollensellerie", "Knollensellerie", "celery root", "raíz de apio"],
        #["koriander", "Koriander", "coriander", "cilantro"],
        #["kraeuter", "Kräuter", "herbs", "hierbas"],
        #["kuerbis", "Kürbis", "pumpkin", "calabaza"],
        #["kuchen", "Kuchen", "cake", "pastel"],
        #["kurkuma", "Kurkuma", "turmeric", "cúrcuma"],
        #["lachs", "Lachs", "salmon", "salmón"],
        #["lorbeer", "Lorbeer", "bayleaf", "laurel"],
        #["lasagneblaetter", "Lasagneblätter", "lasagna sheets", "hojas de lasagna"],
        #["limette", "Limette", "lime", "lima"],
        #["linsen", "Linsen", "lentils", "lentejas"],
        #["macadamia", "Macadamia", "macadamia", "macadamia"],
        #["maisgries", "Maisgries", "corn grits", "sémola de maíz"],
        ["maismehl", g, 3.63, "Maismehl", "corn flour", "harina de maíz"],
        #["maisstaerke", "Maisstärke", "cornstarch", "maicena"],
        #["majoran", "Majoran", "marjoram", "mejorana"],
        #["mandeln", "Mandeln", "almonds", "almendras"],
        #["mandarine", "Mandarine", "mandarin", "mandarina"],
        #["mango", "Mango", "mango", "mango"],
        ["margarine", g, 7.17, "Margarine", "margarine", "margarina"],
        #["mayonnaise", "Mayonnaise", "mayonnaise", "mayonesa"],
        #["meersalz", "Meersalz", "sea salt", "sal de mar"],
        ["mehl", g, 3.54, "Mehl", "flour", "harina"],
        #["mehr", "mehr", "more", "más"],
        #["melone", "Melone", "melon", "melón"],
        #["melasse", "Melasse", "treacle", "melaza"],
        #["mittelgross", "mittelgroß", "normal size", "deporte normal"],
        #["milch", "Milch", "milk", "leche"],
        #["moehre", "Möhre", "carrot", "zanahoria"],
        #["moehren", "Möhren", "carrots", "zanahorias"],
        #["milchprodukte", "Milchprodukte", "dairy products", "productos lácteos"],
        #["minze", "Minze", "mint", "menta"],
        #["mischung", "Mischung", "mix", "mezcla"],
        #["msp", "Messerspitze", "knife tip", "punta de cuchillo"],
        #["muerbeteig", "Mürbeteig", "shortcrust", "pastaflora"],
        #["muskat", "Muskat", "nutmeg", "nuez moscada"],
        #["muskatnuss", "Muskatnuss", "nutmeg", "nuez moscada"],
        #["natron", "Natron", "baking soda", "bicarbonato de sodio"],
        #["nelken", "Nelken", "cloves", "clavos de olor"],
        #["nudeln", "Nudeln", "pasta", "tallarines"],
        #["nuesse", "Nüsse", "nuts", "nueces"],
        #["obst", "Obst", "fruits", "fruta"],
        #["oel", "Öl", "oil", "aceite"],
        #["olivenoel", "Olivenöl", "olive oil", "aceite de oliva"],
        #["orange", "Orange", "orange", "naranja"],
        #["orangenschale", "Orangenschale", "orange peel", "cascara de naranja"],
        #["oregano", "Oregano", "oregano", "orégano"],
        #["passiert", "passiert", "sieved tomatos", "tomates tamizados"],
        #["pakete", "Pakete", "packages", "paquete"],
        #["paranuesse", "Paranüsse", "brazil nuts", "nueces de brazil"],
        #["parmesan", "Parmesan", "parmesan cheese", "queso parmesano"],
        #["paprika", "Paprika", "bellpepper", "pimienton"],
        #["petersilie", "Petersilie", "parsley", "perejil"],
        #["pfeffer", "Pfeffer", "pepper", "pimienta"],
        #["pfefferkuchengewuerz", "Pfefferkuchengewürz", "gingerbread spice", "especias de pan de gengibre"],
        #["pfirsich", "Pfirsich", "peach", "durazno"],
        #["pfirsiche", "Pfirsiche", "peaches", "duraznos"],
        #["pflaume", "Pflaume", "plum", "ciruela"],
        #["pflaumenmuss", "Pflaumenmus", "plum jam", "dulce de ciruela"],
        #["pilze", "Pilze", "mushrooms", "champiñones"],
        #["pistazien", "Pistazien", "pistachios", "pistachos"],
        #["porree", "Porree", "leek", "puerro"],
        #["pumpernickel", "Pumpernickel", "pumpernickel", "pan integral de centeno"],
        #["pumpkinspice", "Pumpkinspice", "pumpkin spice", "pumpkin spice"],
        #["prise", "Prise", "pinch", "pizca"],
        ["puderzucker", g, 4.01, "Puderzucker", "powdered sugar", "azúcar en polvo"],
        #["quark", "Quark", "german curd cheese (Quark)", "requesón alemán (Quark)"],
        #["reis", "Reis", "rice", "arroz"],
        #["rohmarzipan", "Rohmarzipan", "marzipan", "marzapán"],
        #["rohrzucker", "Rohrzucker", "cane sugar", "caña de azúcar"],
        #["rosmarin", "Rosmarin", "rosemary", "romero"],
        #["rosenkohl", "Rosenkohl", "brussels sprouts", "coles de bruselas"],
        #["rosinen", "Rosinen", "raisins", "pasas"],
        #["rotwein", "Rotwein", "red wine", "vino rojo"],
        #["rucola", "Rucola", "arugula", "rúcula"],
        #["rum", "Rum", "rum", "ron"],
        #["saft", "Saft", "juice", "jugo"],
        #["sahne", "Sahne", "whipping cream", "crema"],
        #["salz", "Salz", "salt", "sal"],
        #["sauerteigstarter", "Sauerteigstarter", "sourdough starter", "masa madre"],
        #["sauresahne", "saure Sahne", "sour cream", "crema ácida"],
        #["schafskaese", "Schafskäse", "feta", "feta"],
        #["schalotten", "Schalotten", "shallots", "chalotes"],
        #["scheiben", "Scheiben", "slices", "laminas"],
        #["schlagsahne", "Schlagsahne", "whipping cream", "creama batida"],
        #["schnittlauch", "Schnittlauch", "chives", "cebollín"],
        #["schokodrops", "Schokodrops", "chocolate drops", "gotas de chocolate"],
        #["schokolade", "Schokolade", "chocolate", "chocolate"],
        #["schote", "Schote", "pod", "vaina"],
        #["seelachs", "Seelachs", "coalfish", "carbonero"],
        #["senf", "Senf", "mustard", "mostaza"],
        #["sirup", "Sirup", "syrup", "jarabe"],
        #["sojamilch", "Sojamilch", "soy milk", "leche de soja"],
        #["sonnenblumenoel", "Sonnenblumenöl", "sunflower oil", "aceite de giraflor"],
        #["sosse", "Soße", "sauce", "salsa"],
        #["spargel", "Spargel", "asparagus", "esparrago"],
        #["speck", "Speck", "bacon", "tocino"],
        ["speisestaerke", g, 3.51, "Speisestärke", "starch", "almidón"],
        #["spinat", "Spinat", "spinach", "espinacas"],
        #["spitzpaprika", "Spitzpaprika", "pointed peppers", "pimientos puntiagudos"],
        #["stange", "Stange", "stick", "tallo"],
        #["stangensellerie", "Stangensellerie", "celery sticks", "tallos de apio"],
        #["starter", "Starter", "starter", "starter"],
        #["stiele", "Stiele", "stems", "tallos"],
        #["suesskartoffel", "Süßkartoffel", "sweet potato", "camote"],
        #["tee", "Tee", "tea", "té"],
        #["teig", "Teig", "dough", "masa"],
        #["teller", "Teller", "plate", "plato"],
        #["thymian", "Thymian", "thyme", "tomillo"],
        #["tofu", "Tofu", "tofu", "tofu"],
        #["toastbrot", "Toastbrot", "toast", "pan tostado"],
        #["tomate", "Tomate", "tomato", "tomate"],
        #["tomaten", "Tomaten", "tomatos", "tomates"],
        #["tomatenmark", "Tomatenmark", "tomato paste", "pasta de tomate"],
        #["tomatensosse", "Tomatensoße", "tomato sauce", "salsa de tomate"],
        #["topping", "Topping", "topping", "topping"],
        #["trockenfruechte", "Trockenfrüchte", "dried fruit", "frutos secos"],
        #["trockenhefe", "Trockenhefe", "dry yeast", "levadura seca"],
        #["vanille", "Vanille", "vanilla", "vainilla"],
        #["vanilleschote", "Vanilleschote", "vanilla pod", "vaina de vainilla"],
        #["vanillezucker", "Vanillezucker", "vanilla sugar", "azúcar de vainilla"],
        #["vanilleextrakt", "Vanilleextrakt", "vanilla extract", "extracto de vainilla"],
        #["vollkorn", "Vollkorn", "whole grain", "integral"],
        #["vollkornmehl", "Vollkornmehl", "wholemeal flour", "harina integral"],
        #["walnuesse", "Walnüsse", "walnuts", "nueces"],
        #["walnuss", "Walnuss", "walnut", "nuez"],
        #["wasser", "Wasser", "water", "agua"],
        #["wein", "Wein", "wine", "vino"],
        #["weintrauben", "Weintrauben", "grapes", "uva"],
        #["Weiss", "weiß", "white", "blanco"],
        #["weisskohl", "Weißkohl", "white cabbage", "repollo blanco"],
        #["weisswein", "Weißwein", "white wine", "vino blanco"],
        #["weizenmehl", "Weizenmehl", "wheat flour", "harina de trigo"],
        #["weizenvollkornmehl", "Weizenvollkornmehl", "wholemeal wheat flour", "harina de trigo integral"],
        #["zehe", "Zehe", "clove", "diente"],
        #["zehen", "Zehen", "cloves", "dientes"],
        #["zeste", "Zeste", "zeste", "zeste"],
        #["zimt", "Zimt", "cinnamon", "canela"],
        #["zitrone", "Zitrone", "lemon", "limones"],
        #["zitronen", "Zitronen", "lemons", "limones"],
        #["zitronensaft", "Zitronensaft", "lemon juice", "jugo de limón"],
        #["zucchini", "Zucchini", "zucchini", "calabacín"],
        ["zucker", g, 4.00, "Zucker", "sugar", "azúcar"],
        #["zwiebel", "Zwiebel", "onion", "cebolla"],
        #["zwiebeln", "Zwiebeln", "onions", "cebollas"],
        ]

class food:

    def __init__(self, f):
        self.name = f[0]
        self.unit = f[1]
        self.cals = f[2]
        self.german = f[3]
        self.english = f[4]
        self.spanish = f[5]

    def __str__(self):
        return self.name


for f in food_list:
    var = food(f)
    globals()[var.name] = var
    del var

